In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("../Datasets/npl_dataset.csv")
df.sample(5)

,Unnamed: 0,match_id,inning,batting_team,bowling_team,ball_over,ball_result,bowler,batsman,non_striker,...,player_dismissed,dismissal_kind,fielder,batsman_runs,wide_runs,bye_runs,legbye_runs,noball_runs,extra_runs,total_runs
7784,7784,2025_2,1,Karnali Yaks,Chitwan Rhinos,11.5,1,Ravi Bopara,Mark Watt,Priyank Panchal,...,NaN,NaN,NaN,1,0,0,0,0,0,1
915,915,2024_5,1,Chitwan Rhinos,Pokhara Avengers,2.3,0,Bipin Khatri,Hassan Eisakhil,Luc Benkenstein,...,NaN,NaN,NaN,0,0,0,0,0,0,0
9509,9509,2025_9,2,Janakpur Bolts,Biratnagar Kings,8.3,0,Sandeep Lamichhane,Jan Nicol Loftie-Eaton,Sanjay Krishnamurthi,...,NaN,NaN,NaN,0,0,0,0,0,0,0
9228,9228,2025_8,1,Kathmandu Gorkhas,Biratnagar Kings,19.4,4,Pratish GC,Mohammad Aadil Alam,John Simpson,...,NaN,NaN,NaN,4,0,0,0,0,0,4
694,694,2024_4,1,Sudurpaschim Royals,Biratnagar Kings,3.1,0,Pratish GC,Binod Bhandari,Brandon McMullen,...,NaN,NaN,NaN,0,0,0,0,0,0,0

In [10]:
#Most Catches Taken

catch_df = df[df["dismissal_kind"] == "caught"]
total_catch = catch_df.groupby("fielder").size().reset_index(name="Catches").sort_values(by="Catches" , ascending=False)
total_catch.head(10)

                 fielder  Catches
65          Sam Heazlett       11
19  Dipendra Singh Airee       10
38          Kushal Malla        8
46          Milind Kumar        7
71      Scott Kuggeleijn        7
23       Gerhard Erasmus        7
79          Sundeep Jora        7
89       †Binod Bhandari        7
37        Kushal Bhurtel        6
35        Kiran Thagunna        6

In [18]:
#Most Run Outs

runout_df = df[df["dismissal_kind"] == "run out"]
total_runouts = runout_df.groupby("fielder").size().reset_index(name="Runouts").sort_values(by="Runouts" , ascending=False)
total_runouts.head(10)

                                fielder  Runouts
4                  Dipendra Singh Airee        3
7          Ishan Pandey/†Binod Bhandari        2
20                          Shahab Alam        2
2                           Bhim Sharki        1
3          Dipendra Rawat/†Arjun Gharti        1
5            Hikmat Mahara/Puneet Mehra        1
1                          Aasif Sheikh        1
6         Ishan Pandey/Scott Kuggeleijn        1
8           JJ Smit/†Niroshan Dickwella        1
9   Jan Nicol Loftie-Eaton/Rupesh Singh        1

In [30]:
#Most Stumped
stumpped_df = df[df["dismissal_kind"] == "stumped"]
total_stumpped = stumpped_df.groupby("fielder").size().reset_index(name="Stumpped").sort_values(by="Stumpped" , ascending=False)
total_stumpped.head(10)

               fielder  Stumpped
2        †John Simpson         4
0     †Adam Rossington         3
1      †Binod Bhandari         3
4  †Niroshan Dickwella         2
3          †Lokesh Bam         1
5       †Ranjeet Kumar         1
6         †Sahil Patel         1
7          †Sameer Ali         1