In [112]:
import pandas as pd

In [113]:
df = pd.read_csv("../Datasets/npl_dataset.csv")

In [120]:
#For most runs
most_runs = df.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).head()
most_runs

batsman
Rohit Paudel            555
Ravi Bopara             523
Binod Bhandari          499
Saif Zaib               391
Dipendra Singh Airee    389
Name: batsman_runs, dtype: int64

In [121]:
#Most Sixes
mask = df["batsman_runs"] == 6
new_df = df[mask]
new_df["batsman"].value_counts().head()

batsman
James Neesham           31
Ravi Bopara             24
Lokesh Bam              23
Dipendra Singh Airee    21
Kushal Malla            21
Name: count, dtype: int64

In [122]:
#Most Fours
mask = df["batsman_runs"] == 4
new_df = df[mask]
new_df["batsman"].value_counts().head()

batsman
Rohit Paudel       44
Binod Bhandari     42
Lahiru Milantha    38
Ravi Bopara        36
Adam Rossington    31
Name: count, dtype: int64

In [123]:
#Highest Scores
result = (
        df.groupby(["match_id", "batsman"])["batsman_runs"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
        .drop_duplicates(subset="match_id", keep="first")
        [["batsman", "batsman_runs"]]
        .head(5)
)
result

           batsman  batsman_runs
0        Mark Watt           114
1  Adam Rossington           108
2     Andries Gous           104
4        Saif Zaib            90
5  Priyank Panchal            90

In [124]:
#Most Hundreds
total_runs = df.groupby(["match_id" , "batsman"])["batsman_runs"].sum().reset_index(name="runs")
hundreds = total_runs[total_runs["runs"]>100]
hundreds["batsman"].value_counts().reset_index()

           batsman  count
0     Andries Gous      1
1  Adam Rossington      1
2        Mark Watt      1

In [128]:
#Most Fifties
total_runs = df.groupby(["match_id" , "batsman"])["batsman_runs"].sum().reset_index(name="runs")
fifties = total_runs[(total_runs["runs"]>50) & (total_runs["runs"]<100)]
fifties["batsman"].value_counts().reset_index()

                 batsman  count
0            Ravi Bopara      6
1         Binod Bhandari      3
2        Lahiru Milantha      2
3           Rohit Paudel      2
4         Martin Guptill      2
5        William Bosisto      2
6               Anil Sah      2
7           Basir Ahamad      2
8              Saif Zaib      2
9             Lokesh Bam      2
10       Priyank Panchal      2
11        Kushal Bhurtel      2
12         James Neesham      2
13       Adam Rossington      2
14            Dev Khanal      1
15         Dinesh Kharel      1
16           Bibek Yadav      1
17   Jaykishan Kolsawala      1
18          Kushal Malla      1
19        Saad Bin Zafar      1
20  Dipendra Singh Airee      1
21        Shikhar Dhawan      1
22      Brandon McMullen      1
23      Stephen Eskinazi      1
24       Hassan Eisakhil      1
25          John Simpson      1
26          Aasif Sheikh      1
27            Arjun Saud      1
28          Ishan Pandey      1
29          Maaz Sadaqat      1
30             Mark Watt      1
31          D'Arcy Short      1
32           Dawid Malan      1
33      Ben Charlesworth      1
34           Bhim Sharki      1
35            Chris Lynn      1
36          Rishi Dhawan      1
37          Sam Heazlett      1
38  Sanjay Krishnamurthi      1
39         Harmeet Singh      1
40            Josh Brown      1

In [127]:
#Best Batting Strike Rate

#Calculate Total Runs
total_runs = df.groupby(["batsman"])["batsman_runs"].sum().reset_index(name = "runs")

#Calculate Total Balls
legal_balls = df[df["wide_runs"]==0] #exclude wide
total_balls = legal_balls.groupby("batsman").size().reset_index(name="balls")
eligible_batsman = total_balls[total_balls["balls"] > 10] #mimium 10 balls played

#Calculate Average
combined = total_runs.merge(eligible_batsman , on="batsman")
combined["strike_rate"] = (combined["runs"] / combined["balls"])*100
combined.sort_values(by="strike_rate" , ascending=False).head()

            batsman  runs  balls  strike_rate
34   Dan Douthwaite    73     39   187.179487
61    James Neesham   346    187   185.026738
93        Nar Sarki    22     12   183.333333
111    Rishi Dhawan    54     31   174.193548
65     John Simpson   172    103   166.990291